### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by arokem** [SlugocM/bayesfit#1]
The installation method [described in the documentation](http://www.slugocm.ca/bayesfit/installation.html#method-1-pip-install-bayesfit) does not install the required dependencies, so these need to be installed separately (e.g. with `pip install -r requirements.txt`).

**Comment by mslugocki** [comment]
I apologize for the long delay.  Life got busy.... 

You are absolutely right.  I will update the documentation for this version, and make these packages required during installation for newest version.  Will close once I resolve these issues at start of next week.

**Comment by mslugocki** [comment]
A pull request from @igordertigor has been accepted and merged into the main branch that resolves this issue by adding these dependencies into the setup.py file.
