### ISSUE TITLE
Support for appearence-based tasks?

### ISSUE THREAD

**Issue by LegrandNico** [SlugocM/bayesfit#10]
Is it possible to use Bayesfit in the context of appearance-based tasks?

![](https://upload.wikimedia.org/wikipedia/commons/d/d0/Psychometric_function_with_artificial_data.png)

I tried to set `nafc` to 1 but get an error.

I can work on a PR if this is not currently supported.

**Comment by mslugocki** [comment]
Think you mean a detection task 💡 

You can set the parameter estimate for gamma to be 0.0, and fix it.  Unfortunately not able to update this code base as a result of contractual obligations, so PRs are always welcome :) 

Hope this helps! 
M 


WORKING EXAMPLE: 
```

import matplotlib.pyplot as plt 
import numpy as np
import bayesfit as bf

stimulus_intensity = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
trial_correct = [1, 3, 4, 8, 7, 8, 10, 10]
trial_total = [10, 10, 10, 10, 10, 10, 10, 10]

data = np.array([stimulus_intensity, trial_correct, trial_total]).transpose()
param_free = [True, True, False, False]
param_ests = [None, None, 0.0, 0.05]

metrics, options = bf.fitmodel(data, 
                               nafc = 2, 
                               sigmoid_type = "logistic", 
                               param_free = param_free,
                               param_ests = param_ests)

bf.plot_psyfcn(data, options, metrics)
```

![Example_Figure](https://user-images.githubusercontent.com/22335130/124343895-ebe84a80-db83-11eb-8596-79243779e74e.png)

**Comment by LegrandNico** [comment]
Thank you for your response, I will try this solution.
