### ISSUE TITLE
Error in documentation for threshold

### ISSUE THREAD

**Issue by pitbull36** [SlugocM/bayesfit#11]
HI Michael, thanks for this package! 
I just wanted to highlight a minor edit required for the API doc for the threshold function (get_threshold.html):

original:
bayesfit.get_threshold(data, metrics, options, threshold_pc, estimate_type = 'MAP')

proposed change:
bayesfit.get_threshold(data, **options, metrics**, threshold_pc, estimate_type = 'MAP')

**Comment by mslugocki** [comment]
Thanks for heads-up!  Corrected. 

✌️ 
- M
