### ISSUE TITLE
import is painfully slow

### ISSUE THREAD

**Issue by schlich** [SlugocM/bayesfit#12]
Importing the module i.e. `from bayesfit import fitmodel` seems to take up to 30 seconds. This is severely interrupting my development workflow including running tests.

**Comment by schlich** [comment]
one thing i noticed is that bayesfit imports matplotlib despite the fact that i dont need matplotlib... perhaps the plotting module should be separated from the fitmodel module

**Comment by mslugocki** [comment]
None of the automated tests, nor personal computers exhibit these issues that you describe.  Suggestions are welcome in the form of pull requests.

**Comment by mslugocki** [comment]
@schlich Can you please provide:

- Operating System
- Version of BayesFit for issue raised
- cProfile of import times (see https://stackoverflow.com/questions/34755728/profile-python-import-times)
- Expectations of what an appropriate import time is given the issue you raised

We can start quantitatively documenting, and then start addressing the issue that you raised.  Without data and expectations, hard to interpret what changes may be needed.

**Comment by mslugocki** [comment]
Output from `python -X importtime bayesfit.py ` posted below for documentation purposes.  Performed on Apple M2, macOS version 13.5.  Bayesfit version 2.3.  

import time: self [us] | cumulative | imported package
import time:       159 |        159 |   _io
import time:        26 |         26 |   marshal
import time:       303 |        303 |   posix
import time:       301 |        788 | _frozen_importlib_external
import time:       821 |        821 |   time
import time:       123 |        944 | zipimport
import time:        46 |         46 |     _codecs
import time:       298 |        344 |   codecs
import time:       577 |        577 |   encodings.aliases
import time:       994 |       1913 | encodings
import time:       229 |        229 | encodings.utf_8
import time:        66 |         66 | _signal
import time:        21 |         21 |     _abc
import time:       107 |        127 |   abc
import time:       127 |        254 | io
import time:        40 |         40 |       _stat
import time:        39 |         78 |     stat
import time:       619 |        619 |     _collections_abc
import time:        25 |         25 |       genericpath
import time:        36 |         61 |     posixpath
import time:       230 |        986 |   os
import time:        46 |         46 |   _sitebuiltins
import time:      1266 |       1266 |   _distutils_hack
import time:       384 |        384 |   types
import time:       249 |        249 |       warnings
import time:       160 |        408 |     importlib
import time:       210 |        210 |     importlib._abc
import time:        90 |         90 |         itertools
import time:       152 |        152 |         keyword
import time:        49 |         49 |           _operator
import time:       254 |        303 |         operator
import time:       163 |        163 |         reprlib
import time:        41 |         41 |         _collections
import time:       842 |       1589 |       collections
import time:        37 |         37 |         _functools
import time:       562 |        598 |       functools
import time:       676 |       2862 |     contextlib
import time:        85 |       3563 |   importlib.util
import time:        42 |         42 |   importlib.machinery
import time:       137 |        137 |   sitecustomize
import time:        72 |         72 |   usercustomize
import time:      3437 |       9930 | site
import time:      1719 |       1719 |     enum
import time:      1494 |       3212 |   numpy._globals
import time:      2579 |       2579 |   numpy.__config__
import time:       816 |        816 |   numpy._distributor_init
import time:       500 |        500 |       __future__
import time:        39 |         39 |                 _sre
import time:       184 |        184 |                   re._constants
import time:       287 |        471 |                 re._parser
import time:        92 |         92 |                 re._casefix
import time:       216 |        816 |               re._compiler
import time:       124 |        124 |               copyreg
import time:       334 |       1273 |             re
import time:       328 |        328 |               _json
import time:       371 |        698 |             json.scanner
import time:       307 |       2277 |           json.decoder
import time:       293 |        293 |           json.encoder
import time:       145 |       2714 |         json
import time:       450 |       3164 |       numpy._version
import time:       796 |       4458 |     numpy.version
import time:       904 |        904 |             math
import time:       543 |        543 |             _datetime
import time:      1572 |       3017 |           datetime
import time:    900732 |     903749 |         numpy.core._multiarray_umath
import time:      1221 |       1221 |             numpy.compat._inspect
import time:       210 |        210 |                 fnmatch
import time:        84 |         84 |                   _winapi
import time:        72 |         72 |                   nt
import time:        66 |         66 |                   nt
import time:        64 |         64 |                   nt
import time:        62 |         62 |                   nt
import time:        62 |         62 |                   nt
import time:        87 |        494 |                 ntpath
import time:        52 |         52 |                 errno
import time:       163 |        163 |                   urllib
import time:      1749 |       1749 |                   ipaddress
import time:      1212 |       3124 |                 urllib.parse
import time:       977 |       4855 |               pathlib
import time:        91 |         91 |               pickle5
import time:       482 |        482 |                   _struct
import time:       176 |        657 |                 struct
import time:       815 |        815 |                 _compat_pickle
import time:     20153 |      20153 |                 _pickle
import time:       108 |        108 |                     org
import time:        18 |        125 |                   org.python
import time:        20 |        145 |                 org.python.core
import time:      1567 |      23336 |               pickle
import time:       906 |      29186 |             numpy.compat.py3k
import time:      1893 |      32299 |           numpy.compat
import time:        19 |      32317 |         numpy.compat._inspect
import time:       806 |     936871 |       numpy.core.overrides
import time:      1131 |     938002 |     numpy.core.multiarray
import time:       822 |        822 |     numpy.core.umath
import time:       232 |        232 |       numbers
import time:       664 |        664 |       numpy.core._string_helpers
import time:       858 |        858 |         numpy.core._dtype
import time:       651 |       1508 |       numpy.core._type_aliases
import time:       709 |       3111 |     numpy.core.numerictypes
import time:       645 |        645 |             numpy.core._exceptions
import time:       132 |        132 |               collections.abc
import time:     11913 |      11913 |                 _contextvars
import time:       677 |      12590 |               contextvars
import time:       739 |      13460 |             numpy.core._ufunc_config
import time:       788 |      14892 |           numpy.core._methods
import time:      5593 |      20485 |         numpy.core.fromnumeric
import time:       772 |      21256 |       numpy.core.shape_base
import time:       815 |        815 |       numpy.core.arrayprint
import time:       699 |        699 |       numpy.core._asarray
import time:      1092 |      23861 |     numpy.core.numeric
import time:       827 |        827 |     numpy.core.defchararray
import time:       825 |        825 |     numpy.core.records
import time:       487 |        487 |     numpy.core.memmap
import time:       374 |        374 |     numpy.core.function_base
import time:       214 |        214 |     numpy.core._machar
import time:       776 |        776 |     numpy.core.getlimits
import time:       605 |        605 |     numpy.core.einsumfunc
import time:     87675 |      87675 |       numpy.core._multiarray_tests
import time:      1405 |      89079 |     numpy.core._add_newdocs
import time:      1483 |       1483 |     numpy.core._add_newdocs_scalars
import time:       612 |        612 |     numpy.core._dtype_ctypes
import time:        31 |         31 |         _ast
import time:       557 |        587 |       ast
import time:     31605 |      31605 |         _ctypes
import time:       959 |        959 |         ctypes._endian
import time:       675 |      33238 |       ctypes
import time:       965 |      34790 |     numpy.core._internal
import time:       602 |        602 |     numpy._pytesttester
import time:      1496 |    1102414 |   numpy.core
import time:       770 |        770 |     numpy.lib.mixins
import time:       613 |        613 |         numpy.lib.ufunclike
import time:      1312 |       1925 |       numpy.lib.type_check
import time:      1199 |       3124 |     numpy.lib.scimath
import time:       499 |        499 |                 numpy.lib.stride_tricks
import time:       525 |       1024 |               numpy.lib.twodim_base
import time:     89078 |      89078 |               numpy.linalg._umath_linalg
import time:       855 |      90955 |             numpy.linalg.linalg
import time:       770 |      91725 |           numpy.linalg
import time:       526 |      92250 |         numpy.matrixlib.defmatrix
import time:       632 |      92882 |       numpy.matrixlib
import time:      1007 |       1007 |         numpy.lib.histograms
import time:      2158 |       3164 |       numpy.lib.function_base
import time:       713 |      96758 |     numpy.lib.index_tricks
import time:       648 |        648 |     numpy.lib.nanfunctions
import time:       995 |        995 |     numpy.lib.shape_base
import time:       707 |        707 |     numpy.lib.polynomial
import time:       493 |        493 |       textwrap
import time:       819 |       1312 |     numpy.lib.utils
import time:       659 |        659 |     numpy.lib.arraysetops
import time:       131 |        131 |         _weakrefset
import time:       274 |        405 |       weakref
import time:       691 |        691 |       numpy.lib.format
import time:       587 |        587 |       numpy.lib._datasource
import time:       308 |        308 |       numpy.lib._iotools
import time:       688 |       2677 |     numpy.lib.npyio
import time:       252 |        252 |     numpy.lib.arrayterator
import time:       447 |        447 |     numpy.lib.arraypad
import time:       691 |        691 |     numpy.lib._version
import time:      1043 |     110077 |   numpy.lib
import time:     86835 |      86835 |       numpy.fft._pocketfft_internal
import time:       410 |      87244 |     numpy.fft._pocketfft
import time:      1700 |       1700 |     numpy.fft.helper
import time:       414 |      89357 |   numpy.fft
import time:       869 |        869 |       numpy.polynomial.polyutils
import time:       697 |        697 |       numpy.polynomial._polybase
import time:      1100 |       2665 |     numpy.polynomial.polynomial
import time:       553 |        553 |     numpy.polynomial.chebyshev
import time:       576 |        576 |     numpy.polynomial.legendre
import time:       666 |        666 |     numpy.polynomial.hermite
import time:       490 |        490 |     numpy.polynomial.hermite_e
import time:       314 |        314 |     numpy.polynomial.laguerre
import time:      1164 |       6426 |   numpy.polynomial
import time:       569 |        569 |             backports_abc
import time:    113828 |     114397 |           numpy.random._common
import time:      1252 |       1252 |               binascii
import time:       512 |       1763 |             base64
import time:    102779 |     102779 |               _hashlib
import time:     10841 |      10841 |                 _blake2
import time:      1025 |      11865 |               hashlib
import time:      1228 |     115872 |             hmac
import time:       724 |        724 |                 _bisect
import time:       286 |       1010 |               bisect
import time:       702 |        702 |               _random
import time:       641 |        641 |               _sha512
import time:       898 |       3250 |             random
import time:      1839 |     122723 |           secrets
import time:       906 |        906 |           threading
import time:     90994 |     329018 |         numpy.random.bit_generator
import time:     86429 |      86429 |         numpy.random._bounded_integers
import time:     89528 |      89528 |         numpy.random._mt19937
import time:     86666 |     591640 |       numpy.random.mtrand
import time:     93361 |      93361 |       numpy.random._philox
import time:     91555 |      91555 |       numpy.random._pcg64
import time:     90177 |      90177 |       numpy.random._sfc64
import time:     89289 |      89289 |       numpy.random._generator
import time:       738 |     956757 |     numpy.random._pickle
import time:       665 |     957421 |   numpy.random
import time:      1680 |       1680 |   numpy.ctypeslib
import time:       688 |        688 |             _opcode
import time:       474 |       1162 |           opcode
import time:       901 |       2062 |         dis
import time:       272 |        272 |             token
import time:      1181 |       1452 |           tokenize
import time:       258 |       1710 |         linecache
import time:      2502 |       6274 |       inspect
import time:      4281 |      10555 |     numpy.ma.core
import time:      1297 |       1297 |     numpy.ma.extras
import time:      1190 |      13040 |   numpy.ma
import time:      5984 |    2293002 | numpy
import time:        40 |         40 |   atexit
import time:        68 |         68 |     _locale
import time:       931 |        998 |   locale
import time:       584 |        584 |     traceback
import time:        33 |         33 |       _string
import time:       731 |        763 |     string
import time:      1779 |       3126 |   logging
import time:       151 |        151 |             org
import time:        12 |        162 |           org.python
import time:        11 |        172 |         org.python.core
import time:       215 |        386 |       copy
import time:       569 |        955 |     dataclasses
import time:       714 |       1669 |   pprint
import time:       576 |        576 |     zlib
import time:       222 |        222 |       _compression
import time:       742 |        742 |       _bz2
import time:       233 |       1196 |     bz2
import time:       990 |        990 |       _lzma
import time:       250 |       1239 |     lzma
import time:       586 |       3596 |   shutil
import time:       504 |        504 |     signal
import time:       547 |        547 |     fcntl
import time:        90 |         90 |     msvcrt
import time:       670 |        670 |     _posixsubprocess
import time:       520 |        520 |     select
import time:       503 |        503 |     selectors
import time:       508 |       3339 |   subprocess
import time:       302 |        302 |   tempfile
import time:       717 |        717 |     packaging
import time:       399 |        399 |       _typing
import time:      2370 |       2768 |     typing
import time:       337 |        337 |     packaging._structures
import time:      1998 |       5819 |   packaging.version
import time:       831 |        831 |     matplotlib._api.deprecation
import time:      1355 |       2186 |   matplotlib._api
import time:      1038 |       1038 |   matplotlib._version
import time:       703 |        703 |     gzip
import time:       492 |        492 |     shlex
import time:     92765 |      92765 |     matplotlib._c_internal_utils
import time:      1524 |      95483 |   matplotlib.cbook
import time:      1732 |       1732 |   matplotlib._docstring
import time:       636 |        636 |         PIL._version
import time:      1313 |       1948 |       PIL
import time:       618 |        618 |                   xml
import time:       404 |       1022 |                 xml.parsers
import time:     18053 |      18053 |                 pyexpat
import time:       615 |      19688 |               xml.parsers.expat
import time:       877 |      20565 |             defusedxml.common
import time:       901 |      21466 |           defusedxml
import time:       637 |        637 |             xml.etree
import time:       834 |        834 |             xml.etree.ElementPath
import time:     13489 |      13489 |             _elementtree
import time:      1031 |      15989 |           xml.etree.ElementTree
import time:         4 |          4 |           _elementtree
import time:       855 |      38312 |         defusedxml.ElementTree
import time:      2226 |       2226 |         PIL.ExifTags
import time:       652 |        652 |         PIL.ImageMode
import time:      1026 |       1026 |         PIL.TiffTags
import time:       513 |        513 |         PIL._binary
import time:       372 |        372 |         PIL._deprecate
import time:       297 |        297 |         PIL._util
import time:    230200 |     230200 |         PIL._imaging
import time:       291 |        291 |             cffi.lock
import time:       339 |        339 |             cffi.error
import time:       603 |        603 |             cffi.model
import time:      1035 |       2266 |           cffi.api
import time:       838 |       3103 |         cffi
import time:      1544 |     278241 |       PIL.Image
import time:       449 |        449 |         PIL.ImageChops
import time:       792 |        792 |         PIL.ImageFile
import time:       359 |        359 |           array
import time:       589 |        589 |           PIL.GimpGradientFile
import time:       520 |        520 |           PIL.GimpPaletteFile
import time:       251 |        251 |           PIL.ImageColor
import time:       281 |        281 |           PIL.PaletteFile
import time:       706 |       2705 |         PIL.ImagePalette
import time:       313 |        313 |         PIL.ImageSequence
import time:       992 |       5249 |       PIL.PngImagePlugin
import time:      1470 |       1470 |       matplotlib._cm
import time:    107856 |     107856 |             matplotlib._path
import time:      1907 |       1907 |               matplotlib.bezier
import time:      2619 |       4525 |             matplotlib.path
import time:      2065 |     114445 |           matplotlib.transforms
import time:      1987 |     116432 |         matplotlib.ticker
import time:      1390 |     117821 |       matplotlib.scale
import time:      1788 |       1788 |       matplotlib._color_data
import time:      2315 |     408829 |     matplotlib.colors
import time:       622 |        622 |         pyparsing.util
import time:       792 |        792 |           pyparsing.unicode
import time:      2081 |       2873 |         pyparsing.exceptions
import time:       392 |        392 |         pyparsing.actions
import time:      1117 |       1117 |           pyparsing.results
import time:      8447 |       9563 |         pyparsing.core
import time:      1396 |       1396 |               html.entities
import time:       799 |       2194 |             html
import time:        11 |       2205 |           html.entities
import time:      2219 |       4424 |         pyparsing.helpers
import time:       422 |        422 |         pyparsing.testing
import time:      2830 |       2830 |         pyparsing.common
import time:      1976 |      23100 |       pyparsing
import time:      1184 |      24284 |     matplotlib._fontconfig_pattern
import time:      1112 |       1112 |     matplotlib._enums
import time:      1300 |       1300 |     cycler
import time:      1480 |     437003 |   matplotlib.rcsetup
import time:    211568 |     211568 |   matplotlib.ft2font
import time:       977 |        977 |   dateutil._version
import time:    163232 |     163232 |   kiwisolver._cext
import time:      3090 |       3090 |     matplotlib._cm_listed
import time:      6520 |       9610 |   matplotlib.cm
import time:     15723 |     957432 | matplotlib

**Comment by schlich** [comment]
Thanks for looking into this @mslugocki ... I think i was just having general problems with package management.  Thank you for looking into it anyways 🙏

**Comment by mslugocki** [comment]
@schlich Appreciate the feedback, and thank you for taking the time in raising the issue.  My first response was not constructive, and so moving forward will take responsibility as the owner to pay the respect deserved to each issue raised, providing greater guidance where required (I certainly hope to learn from others expertise).  

Regarding the issue itself:  I think optimization is important.  Instead of adding additional features, believe BayesFit is in the perfect position to keep the API the same, but optimize the performance.  Will see what I can do while seeking employment in the meantime. 

Kind Regards,
Michael

**Comment by schlich** [comment]
I'm glad to see this package is still being maintained; I started development on [PsychoAnalyze](https://github.com/psychoanalyze/psychoanalyze) for want of a better Python ecosystem in psychophysics.  It would be a huge weight lifted off if it could rely on bayesfit for internals

@mslugocki

**Comment by mslugocki** [comment]
Very cool!  Look forward to keeping track of PsychoAnalyze, and love that the ecosystem for psychophysics is being built out.  Was always the hope that BayesFit can continue being of use to the research community, and helps me to focus on optimization of the existing code base given such great projects are expanding in the field of psychophysics.
